### ISSUE TITLE
Failed to decode the unity prefab due to an error

### ISSUE THREAD

**Issue by ghost** [dfgHiatus/ResoniteUnityPackagesImporter#27]
i am trying to import a vrchat avatar but i cannot import the .unitypackage file because it says "Failed to decode the unity prefab due to an error" and at the bottom it says:
"instanciated 817 unity objects/components/meshes for prefab! Now cleaning up"

altough i couldn't follow the install steps as you cannot access the website where the zip file is contained
it just gives back the error: {"message":"Artifact not found or access denied."}

**Comment by dfgHiatus** [comment]
Thanks for the issue report, can you please attach your latest log here?

**Comment by dfgHiatus** [comment]
Also, if you could attach the unity package here that would be helpful

**Comment by 989onan** [comment]
as the one who wrote the code, it is impossible to debug without the package. thousands of things can go wrong

**Comment by RemoteHun** [comment]
[REMOTEHUN - 2024.5.24.202 - 2024-05-26 18_41_00.log](https://github.com/dfgHiatus/ResoniteUnityPackagesImporter/files/15473917/REMOTEHUN.-.2024.5.24.202.-.2024-05-26.18_41_00.log)

Here is the log and

https://drive.google.com/file/d/1nH6Ks3Mav-3NLWzPiCOGZEgJ2NRf4AI7/view?usp=sharing

here is the unity package file (i had to use google drive because of the size limit)

**Comment by ghost** [comment]
apparently it's missing the fbx model
i placed it in and it works now
